# Generated by Django 5.0 on 2024-01-06 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_task_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='image',
        ),
    ]
